version: '2'
services:
  fluentd:
    image: fluentd1
    links:
      - "elasticsearch"
    ports:
      - "80:80"
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.4.2
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.4.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"